### ISSUE TITLE
Problem using existing Dask code in a Prefect task

### ISSUE THREAD

**Issue by tonycombocurve** [PrefectHQ/prefect-dask#22]
I have some existing code that uses Dask to do simple calculations. After learning about Prefect, I thought it would be helpful for running some of our backend jobs. It seems that prefect_dask fails in my task code whenever compute gets invoked with the following stack trace:

```
08:14:34.929 | ERROR   | asyncio - Exception in callback WorkerThread._report_result(<Future pendi...A52E98F40>()]>, None, StopIteration())
handle: <Handle WorkerThread._report_result(<Future pendi...A52E98F40>()]>, None, StopIteration())>
Traceback (most recent call last):
  File "C:\Users\tony\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\tony\dask-demo\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 849, in _report_result
    future.set_exception(exc)
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```

I am using Prefect 2.0 and the DaskTaskRunner for the flow that invokes this task. Here is my task code:

```
@task
def get_forecast(database_name: str, forecast_id: str) -> dict:
    # read forecast
    forecast_bag: Bag = dask_mongo.read_mongo(
        database=database_name,
        collection='forecasts',
        connection_kwargs={
            'host': __get_host_uri()
        },
        chunksize=1,
        match={
            '_id': ObjectId(forecast_id)
        }
    )
    return forecast_bag.take(1)[0]
```

Any clues as to what is happening?

Thanks in advance for your help!

**Comment by tonycombocurve** [comment]
For the record, I get the same error when running the flow without the DaskTaskRunner.

**Comment by tonycombocurve** [comment]
> Hi! Thanks for reporting this. Was wondering if you could share more of the traceback?

That was the entire traceback. I decided to dig further into DaskTaskRunner and am in the process of trying to pass the address of my existing cluster. Running into issues with the TLS address returned from my cluster. Ultimately, I'm trying to understand the integration between Prefect and Dask. Still some work to do on that...

**Comment by tonycombocurve** [comment]
Interestingly enough, when I put in very simple task logic (borrowed from [here](https://docs.coiled.io/user_guide/getting_started.html)) the flow is executed as expected. There must be something in the dask_mongo implementation this is causing the issue. Will close this issue for now.
