### ISSUE TITLE
Documentation around connecting to a cluster with a `tls://` address

### ISSUE THREAD

**Issue by phobson** [PrefectHQ/prefect-dask#23]
At Coiled, we have several users excited to use Prefect 2.0 with our clusters. Our small OSS team is kicking the tires on Prefect 2.0 as well.

Between our experiences and what we're hearing from our users, there's a small gap in the documentation in how to connect to any cluster (Coiled or otherwise) whose scheduler is at a TLS address.

The current README's example uses a TCP address. But a TLS address appears to be more complicated.

```python
import time

from prefect import task, flow
from prefect_dask.task_runners import DaskTaskRunner
from coiled import Cluster


cluster = Cluster(name="quick-test", package_sync=True)
runner = DaskTaskRunner(address=cluster.scheduler_address)
print(cluster.scheduler_address)


@task(name="shouter")
def shout(number):
    time.sleep(0.5)
    print(f"#{number}")


@flow(task_runner=runner)
def simple_count_to(highest_number):
    for number in range(highest_number):
        shout.submit(number)


if __name__ == "__main__":
    simple_count_to(10)

```

And that prints/raises:

<details>
<summary>TLS Address and trackback</summary>

```
tls://34.226.191.236:8786
09:41:49.052 | INFO    | prefect.engine - Created flow run 'naughty-antelope' for flow 'simple-count-to'
09:41:49.052 | INFO    | prefect.task_runner.dask - Connecting to an existing Dask cluster at tls://34.226.191.236:8786
09:41:49.053 | ERROR   | Flow run 'naughty-antelope' - Crash detected! Execution was interrupted by an unexpected exception.
Traceback (most recent call last):
  File "/Users/paul/work/office-hours/support-metrostar/test_scratch.py", line 27, in <module>
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/prefect/flows.py", line 390, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/prefect/engine.py", line 152, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/prefect/engine.py", line 221, in create_then_begin_flow_run
    state = await begin_flow_run(
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/prefect/engine.py", line 328, in begin_flow_run
    flow_run_context.task_runner = await stack.enter_async_context(
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/contextlib.py", line 575, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/prefect/task_runners.py", line 168, in start
    await self._start(exit_stack)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/prefect_dask/task_runners.py", line 267, in _start
    self._client = await exit_stack.enter_async_context(
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/contextlib.py", line 575, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/distributed/client.py", line 1347, in __aenter__
    await self
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/distributed/client.py", line 1178, in _start
    await self._ensure_connected(timeout=timeout)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/distributed/client.py", line 1241, in _ensure_connected
    comm = await connect(
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/distributed/comm/core.py", line 289, in connect
    comm = await asyncio.wait_for(
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/distributed/comm/tcp.py", line 436, in connect
    kwargs = self._get_connect_args(**connection_args)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/distributed/comm/tcp.py", line 483, in _get_connect_args
    ctx = _expect_tls_context(connection_args)
  File "/Users/paul/mambaforge/envs/hydro/lib/python3.9/site-packages/distributed/comm/tcp.py", line 389, in _expect_tls_context
    raise TypeError(
TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?) Instead got None
```
</details>

The crux of the matter is that distributed needs more information about the scheduler to the `DaskTaskRunner`, specifically an `SSLContext` for the cluster. We're working on cooking up an example right now for our own docs, but I think a minimal example for the README would help Coiled and non-Coiled users alike. 

This issue is to gauge interest in contributing such an example to `prefect_dask` docs. Here are the relevant distributed docs: https://distributed.dask.org/en/stable/tls.html

**Comment by ntabris** [comment]
I think this should work when `cluster` is existing `distributed.deploy.Cluster` with `cluster.security` set:

```
task_runner = DaskTaskRunner(
  address=cluster.scheduler_address,
  client_kwargs={'security': cluster.security}
)
```

Note thought that `security` isn't a required attribute on `distributed.deploy.Cluster`, but I believe this is a standard attribute for clusters that do have TLS keypair set.

I think a really nice API for `DaskTaskRunner` would allow you to pass existing cluster, and have it use `security` if set. This is what happens when you do `client = distributed.Client(cluster=cluster)`, as you can see at https://github.com/dask/distributed/blob/1314ebb8671493290d284bf24b1ed1da1749f90c/distributed/client.py#L846-L847

**Comment by ntabris** [comment]
I put together a quick PR, feel free to use/edit as you see fit.
